<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["cfma002/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["cfma002/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Recnum</th>
            <th>Id Of Palete</th>
            <th>Codpatrimonio</th>
            <th>Descricao</th>
            <th>Codigo Of Barra</th>
            <th>Situacao</th>
            <th>Filial Of Local</th>
            <th>Log</th>
            <th>Log Of Hora</th>
            <th>Log Of Data</th>
            <th>Id Of Ordem</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $cfma002): ?>
            <tr>
                <td><?php echo $cfma002->recnum ?></td>
            <td><?php echo $cfma002->id_palete ?></td>
            <td><?php echo $cfma002->codpatrimonio ?></td>
            <td><?php echo $cfma002->descricao ?></td>
            <td><?php echo $cfma002->codigo_barra ?></td>
            <td><?php echo $cfma002->situacao ?></td>
            <td><?php echo $cfma002->filial_local ?></td>
            <td><?php echo $cfma002->log ?></td>
            <td><?php echo $cfma002->log_hora ?></td>
            <td><?php echo $cfma002->log_data ?></td>
            <td><?php echo $cfma002->id_ordem ?></td>

                <td><?php echo $this->tag->linkTo(["cfma002/edit/" . $cfma002->recnum, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["cfma002/delete/" . $cfma002->recnum, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("cfma002/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("cfma002/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("cfma002/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("cfma002/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
